export const campaigns = [
  {
    subTitle: " We are launching a new drink in Lagos and we need",
    title: "Pepsi Zero:",
    description: "the young Fit Fam audience involved.",
    start: "Mar 1, 2024",
    end: "June 31, 2024",
    image: "/frame1.png",
    users: ["/1.png", "/2.png", "/3.png", "/4.png"],
    progress: 70,
    stats: [
      { label: "VIEWS", value: "90,102,340" },
      { label: "IMPRESSION", value: "3,902,017" },
      { label: "ENGAGEMENT RATE", value: "31%" },
      { label: "TOP AGE", value: "24 - 35 (70%)" },
      { label: "LOCATION", value: "Lagos" },
      { label: "TOTAL AUDIENCE", value: "420,108,021" },
    ],
  },
  {
    subTitle: " We are launching a new drink in Lagos and we need",
    title: "Pepsi Zero:",
    description: "the young Fit Fam audience involved.",
    start: "Mar 1, 2024",
    end: "June 31, 2024",
    image: "/Frame2.png",
    users: ["/1.png", "/2.png", "/3.png", "/4.png"],
    progress: 60,
    stats: [
      { label: "VIEWS", value: "90,102,340" },
      { label: "IMPRESSION", value: "3,902,017" },
      { label: "ENGAGEMENT RATE", value: "31%" },
      { label: "TOP AGE", value: "24 - 35 (70%)" },
      { label: "LOCATION", value: "Lagos" },
      { label: "TOTAL AUDIENCE", value: "420,108,021" },
    ],
  },
  {
    subTitle: " We are launching a new drink in Lagos and we need",
    title: "Pepsi Zero:",
    description: "the young Fit Fam audience involved.",
    start: "Mar 1, 2024",
    end: "June 31, 2024",
    image: "/frame1.png",
    users: ["/1.png", "/2.png", "/3.png", "/4.png"],
    progress: 70,
    stats: [
      { label: "VIEWS", value: "90,102,340" },
      { label: "IMPRESSION", value: "3,902,017" },
      { label: "ENGAGEMENT RATE", value: "31%" },
      { label: "TOP AGE", value: "24 - 35 (70%)" },
      { label: "LOCATION", value: "Lagos" },
      { label: "TOTAL AUDIENCE", value: "420,108,021" },
    ],
  },
  {
    subTitle: " We are launching a new drink in Lagos and we need",
    title: "Pepsi Zero:",
    description: "the young Fit Fam audience involved.",
    start: "Mar 1, 2024",
    end: "June 31, 2024",
    image: "/Frame2.png",
    users: ["/1.png", "/2.png", "/3.png", "/4.png"],
    progress: 60,
    stats: [
      { label: "VIEWS", value: "90,102,340" },
      { label: "IMPRESSION", value: "3,902,017" },
      { label: "ENGAGEMENT RATE", value: "31%" },
      { label: "TOP AGE", value: "24 - 35 (70%)" },
      { label: "LOCATION", value: "Lagos" },
      { label: "TOTAL AUDIENCE", value: "420,108,021" },
    ],
  },
];